# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'home', folder: '', file: '/index.html'}
- {name: 'bio/resume', folder: '/pages', file: '/bio.html'}
- {name: 'research', folder: '/pages', file: '/research.html'}
- {name: 'misc', folder: '/pages', file: '/misc.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:n.linh@nyu.edu'}
#- {icon: 'linkedin', link: 'linkedin.com/in/dam-linh-nguyen-6b1b6b66'}
